env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: 
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
  jsx-a11y/anchor-is-valid:
  - error
  - components:
    - Link
    specialLink:
    - hrefLeft
    - hrefRight
    aspects:
    - invalidHref
    - preferButton
  react/react-in-jsx-scope: 'off'
  no-underscore-dangle:
    - error
    - allow:
      - _id
